## mysql
mysql:
 url: "aa"
 user: root
 password: 123

## druid
#spring:
# datasource:
#  type: com.alibaba.druid.pool.DruidDataSource
#  driver-class-name: com.mysql.jdbc.Driver
#  url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8
#  username: root
#  password: 123
#
#  filters: stat,wall,log4j
#  maxActive: 20
#  initialSize: 1
#  maxWait: 60000
#  poolPreparedStatements: true
#  maxPoolPreparedStatementPerConnectionSize: 20
#  connectionProperties: druid.stat.mergeSql=true;druid.sta